/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: FerrisAttia (https://sketchfab.com/FerrisAttia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-tree-purple-leaves-b6d85e59d1714c7ab3cf40b77a46076f
Title: Fantasy Tree - Purple Leaves
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pur(props) {
  const { nodes, materials } = useGLTF('../drum/pisici/purp/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[2.66, 1.69, 0]} scale={0.68}>
          <group position={[-3.92, -2.49, 0]} scale={1.47}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Trunk} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Trunk} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.Trunk} />
          </group>
        </group>
        <group position={[2.66, 1.69, 0]} scale={0.67}>
          <mesh geometry={nodes.Object_9.geometry} material={materials['01_-_Default']} position={[-3.99, -2.54, 0]} scale={1.5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../drum/pisici/purp/scene-transformed.glb')
